# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\[app]CoolAnaylser\UI\MainWindow.ui'
#
# Created: Mon Jun 20 23:26:03 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainDialog(object):
    def setupUi(self, MainDialog):
        MainDialog.setObjectName(_fromUtf8("MainDialog"))
        MainDialog.resize(1048, 626)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainDialog.sizePolicy().hasHeightForWidth())
        MainDialog.setSizePolicy(sizePolicy)
        self.groupBox = QtGui.QGroupBox(MainDialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 171, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.rbMMS = QtGui.QRadioButton(self.groupBox)
        self.rbMMS.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.rbMMS.setChecked(True)
        self.rbMMS.setObjectName(_fromUtf8("rbMMS"))
        self.rbNewspaper = QtGui.QRadioButton(self.groupBox)
        self.rbNewspaper.setGeometry(QtCore.QRect(10, 50, 89, 16))
        self.rbNewspaper.setObjectName(_fromUtf8("rbNewspaper"))
        self.groupBox_2 = QtGui.QGroupBox(MainDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 130, 211, 401))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.btnOpenDialog = QtGui.QPushButton(self.groupBox_2)
        self.btnOpenDialog.setGeometry(QtCore.QRect(10, 70, 81, 23))
        self.btnOpenDialog.setObjectName(_fromUtf8("btnOpenDialog"))
        self.cbFilterField = QtGui.QComboBox(self.groupBox_2)
        self.cbFilterField.setGeometry(QtCore.QRect(10, 30, 71, 22))
        self.cbFilterField.setObjectName(_fromUtf8("cbFilterField"))
        self.cbFilterValue = QtGui.QComboBox(self.groupBox_2)
        self.cbFilterValue.setGeometry(QtCore.QRect(90, 30, 71, 22))
        self.cbFilterValue.setObjectName(_fromUtf8("cbFilterValue"))
        self.chbFilterMap = QtGui.QCheckBox(self.groupBox_2)
        self.chbFilterMap.setGeometry(QtCore.QRect(110, 74, 91, 16))
        self.chbFilterMap.setChecked(True)
        self.chbFilterMap.setObjectName(_fromUtf8("chbFilterMap"))
        self.lbFiles = QtGui.QListWidget(self.groupBox_2)
        self.lbFiles.setGeometry(QtCore.QRect(10, 110, 181, 311))
        self.lbFiles.setObjectName(_fromUtf8("lbFiles"))
        self.btnAddFilter = QtGui.QPushButton(self.groupBox_2)
        self.btnAddFilter.setGeometry(QtCore.QRect(167, 30, 41, 23))
        self.btnAddFilter.setObjectName(_fromUtf8("btnAddFilter"))
        self.lbProcessor = QtGui.QListWidget(MainDialog)
        self.lbProcessor.setGeometry(QtCore.QRect(230, 210, 281, 181))
        self.lbProcessor.setObjectName(_fromUtf8("lbProcessor"))
        self.groupBox_4 = QtGui.QGroupBox(MainDialog)
        self.groupBox_4.setGeometry(QtCore.QRect(230, 20, 281, 171))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.cbStatField = QtGui.QComboBox(self.groupBox_4)
        self.cbStatField.setGeometry(QtCore.QRect(10, 30, 91, 22))
        self.cbStatField.setObjectName(_fromUtf8("cbStatField"))
        self.cbStatValue = QtGui.QComboBox(self.groupBox_4)
        self.cbStatValue.setGeometry(QtCore.QRect(110, 30, 161, 22))
        self.cbStatValue.setObjectName(_fromUtf8("cbStatValue"))
        self.chbStatMap = QtGui.QCheckBox(self.groupBox_4)
        self.chbStatMap.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.chbStatMap.setChecked(True)
        self.chbStatMap.setObjectName(_fromUtf8("chbStatMap"))
        self.btnAddStat = QtGui.QPushButton(self.groupBox_4)
        self.btnAddStat.setGeometry(QtCore.QRect(200, 70, 51, 23))
        self.btnAddStat.setObjectName(_fromUtf8("btnAddStat"))
        self.cbStatRoutine = QtGui.QComboBox(self.groupBox_4)
        self.cbStatRoutine.setGeometry(QtCore.QRect(10, 60, 91, 21))
        self.cbStatRoutine.setObjectName(_fromUtf8("cbStatRoutine"))
        self.groupBox_3 = QtGui.QGroupBox(MainDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(230, 410, 281, 121))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.rdTxt = QtGui.QRadioButton(self.groupBox_3)
        self.rdTxt.setEnabled(False)
        self.rdTxt.setGeometry(QtCore.QRect(130, 70, 89, 16))
        self.rdTxt.setObjectName(_fromUtf8("rdTxt"))
        self.rdXls = QtGui.QRadioButton(self.groupBox_3)
        self.rdXls.setEnabled(False)
        self.rdXls.setGeometry(QtCore.QRect(130, 90, 89, 16))
        self.rdXls.setObjectName(_fromUtf8("rdXls"))
        self.rdDisplay = QtGui.QRadioButton(self.groupBox_3)
        self.rdDisplay.setEnabled(False)
        self.rdDisplay.setGeometry(QtCore.QRect(130, 50, 91, 16))
        self.rdDisplay.setObjectName(_fromUtf8("rdDisplay"))
        self.edSaveFile = QtGui.QLineEdit(self.groupBox_3)
        self.edSaveFile.setEnabled(True)
        self.edSaveFile.setGeometry(QtCore.QRect(10, 20, 211, 20))
        self.edSaveFile.setObjectName(_fromUtf8("edSaveFile"))
        self.btnProcess = QtGui.QPushButton(self.groupBox_3)
        self.btnProcess.setGeometry(QtCore.QRect(10, 64, 51, 23))
        self.btnProcess.setObjectName(_fromUtf8("btnProcess"))
        self.tabWidget = QtGui.QTabWidget(MainDialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(530, 20, 501, 511))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.edtStatus = QtGui.QTextBrowser(self.tab)
        self.edtStatus.setGeometry(QtCore.QRect(0, 0, 491, 481))
        self.edtStatus.setObjectName(_fromUtf8("edtStatus"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(MainDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainDialog)

    def retranslateUi(self, MainDialog):
        MainDialog.setWindowTitle(QtGui.QApplication.translate("MainDialog", "Cool Analyser", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainDialog", "文件类型", None, QtGui.QApplication.UnicodeUTF8))
        self.rbMMS.setText(QtGui.QApplication.translate("MainDialog", "彩信", None, QtGui.QApplication.UnicodeUTF8))
        self.rbNewspaper.setText(QtGui.QApplication.translate("MainDialog", "手机报", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainDialog", "选择文件和筛选器", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpenDialog.setText(QtGui.QApplication.translate("MainDialog", "选择文件", None, QtGui.QApplication.UnicodeUTF8))
        self.chbFilterMap.setText(QtGui.QApplication.translate("MainDialog", "按组", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddFilter.setText(QtGui.QApplication.translate("MainDialog", "添加", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainDialog", "统计", None, QtGui.QApplication.UnicodeUTF8))
        self.chbStatMap.setText(QtGui.QApplication.translate("MainDialog", "按组", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddStat.setText(QtGui.QApplication.translate("MainDialog", "添加", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainDialog", "报告", None, QtGui.QApplication.UnicodeUTF8))
        self.rdTxt.setText(QtGui.QApplication.translate("MainDialog", "txt", None, QtGui.QApplication.UnicodeUTF8))
        self.rdXls.setText(QtGui.QApplication.translate("MainDialog", "xls", None, QtGui.QApplication.UnicodeUTF8))
        self.rdDisplay.setText(QtGui.QApplication.translate("MainDialog", "display", None, QtGui.QApplication.UnicodeUTF8))
        self.edSaveFile.setText(QtGui.QApplication.translate("MainDialog", "out.xls", None, QtGui.QApplication.UnicodeUTF8))
        self.btnProcess.setText(QtGui.QApplication.translate("MainDialog", "运行", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainDialog", "执行记录", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainDialog = QtGui.QDialog()
    ui = Ui_MainDialog()
    ui.setupUi(MainDialog)
    MainDialog.show()
    sys.exit(app.exec_())

